- name: Adds node PPA key
  apt_key: url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x136221EE520DDFAF0A905689B9316A7BC7917B12 state=present
  tags: nodejs

- name: Adds node PPA
  apt_repository: repo='ppa:chris-lea/node.js' update_cache=yes
  tags: nodejs

- name: Installs nodejs
  apt: pkg=nodejs state=latest
  tags: nodejs
